mqtt:
  topic: "hablistener"
  host: "mosquitto"
  port: 1883
  user: "habmaps"
  password: "habmaps"
strapi:
    host: "http://habmaps_strapi:1337"
    user: "admin"
    password: "password"
    collection: 
      frame: "frames"
      health: "statuses"
      lastseen: "last-seens"
    error_file: "/tmp/errors.log"